export { default as Settings } from "./settings";
export { default as Header } from "./header";
export { default as Footer } from "./footer";
export { default as Layout } from "./layout";
export { default as Menu } from "./menu";
export { default as Button } from "./button";
export { default as Icon } from "./icon";
export { default as Box } from "./box";
export { default as Card } from "./card";
export { default as Image } from "./image";
export { default as Modal } from "./modal";
export { default as Slider } from "./slider";
export { default as Container } from "./container";
export { Device, Mobile, Tablet, Desktop, Widescreen, Screen } from "./device";
export { default as Tabs } from "./tabs";
export { default as suitupable } from "./component";